# Generated by Django 5.2.5 on 2025-09-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('pressure', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('dewpoint', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
    ]
