# Generated by Django 5.2.5 on 2025-09-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='React',
            new_name='Weather',
        ),
    ]
